name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'لینک ویدیوی یوتیوب را وارد کنید'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install -U yt-dlp

    - name: Download Video with Cookies
      env:
        YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
      run: |
        mkdir downloaded_video
        cd downloaded_video
        # ساخت فایل کوکی از سیکرت گیت‌هاب
        echo "$YOUTUBE_COOKIES" > cookies.txt
        # دانلود با استفاده از کوکی
        yt-dlp --cookies cookies.txt -f "bestvideo+bestaudio/best" --merge-output-format mp4 "${{ inputs.video_url }}"

    - name: Upload Video as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YouTube-Video
        path: downloaded_video/
